apiVersion: v1
kind: Namespace
metadata:
  name: dvwa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dvwa
  name: dvwa-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dvwa-app
  template:
    metadata:
      labels:
        app: dvwa-app
    spec:
      containers:
      - name: dvwa
        image: zhinvlu68hao/web-dvwa
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: dvwa
  name: dvwa-service
spec:
  selector:
    app: dvwa-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
