name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
#    - name: Build and push Docker image
#      uses: docker/build-push-action@v2
#      with:
#        context: .
#        push: true
#        tags: zhinvlu68hao/web-dvwa
#        use_enforcement_rules: true

    - name : Build and push DVWA image
      run: |
        docker image build --tag dvwa .
        docker image tag dvwa zhinvlu68hao/web-dvwa
        docker image push zhinvlu68hao/web-dvwa
 
    - name: Log in with Azure
      uses: azure/login@v2.2.0
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        
    - name: Set AKS context
      id: set-context
      uses: azure/aks-set-context@v3
      with:
        resource-group: '${{ secrets.resource_group }}' 
        cluster-name: '${{ secrets.cluster_name }}'
        
    - name: Setup kubectl
      id: install-kubectl
      uses: azure/setup-kubectl@v3
      
    - name: Deploy to AKS
      id: deploy-aks
      uses: Azure/k8s-deploy@v4
      with:
        manifests: |
            deploy.yaml
        images: zhinvlu68hao/web-dvwa
        pull-images: false
